-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [base64_core]: function definitions
import Aeneas
import Verified.Extracted.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace base64_core

/-- [base64_core::PAD_BYTE]
    Source: 'rust/base64-core/src/lib.rs', lines 25:0-25:28
    Visibility: public -/
@[global_simps, irreducible] def PAD_BYTE : Std.U8 := 61#u8

/-- [base64_core::INVALID_VALUE]
    Source: 'rust/base64-core/src/lib.rs', lines 28:0-28:34
    Visibility: public -/
@[global_simps, irreducible] def INVALID_VALUE : Std.U8 := 255#u8

/-- [base64_core::STANDARD_ENCODE]
    Source: 'rust/base64-core/src/lib.rs', lines 40:0-45:2
    Visibility: public -/
@[global_simps, irreducible]
def STANDARD_ENCODE : Array Std.U8 64#usize :=
  Array.make 64#usize [
    65#u8, 66#u8, 67#u8, 68#u8, 69#u8, 70#u8, 71#u8, 72#u8, 73#u8, 74#u8,
    75#u8, 76#u8, 77#u8, 78#u8, 79#u8, 80#u8, 81#u8, 82#u8, 83#u8, 84#u8,
    85#u8, 86#u8, 87#u8, 88#u8, 89#u8, 90#u8, 97#u8, 98#u8, 99#u8, 100#u8,
    101#u8, 102#u8, 103#u8, 104#u8, 105#u8, 106#u8, 107#u8, 108#u8, 109#u8,
    110#u8, 111#u8, 112#u8, 113#u8, 114#u8, 115#u8, 116#u8, 117#u8, 118#u8,
    119#u8, 120#u8, 121#u8, 122#u8, 48#u8, 49#u8, 50#u8, 51#u8, 52#u8, 53#u8,
    54#u8, 55#u8, 56#u8, 57#u8, 43#u8, 47#u8
    ]

/-- [base64_core::STANDARD_DECODE]
    Source: 'rust/base64-core/src/lib.rs', lines 47:0-64:2
    Visibility: public -/
@[global_simps, irreducible]
def STANDARD_DECODE : Array Std.U8 256#usize :=
  Array.make 256#usize [
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 62#u8, 255#u8,
    255#u8, 255#u8, 63#u8, 52#u8, 53#u8, 54#u8, 55#u8, 56#u8, 57#u8, 58#u8,
    59#u8, 60#u8, 61#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 0#u8, 1#u8, 2#u8, 3#u8, 4#u8, 5#u8, 6#u8, 7#u8, 8#u8, 9#u8, 10#u8,
    11#u8, 12#u8, 13#u8, 14#u8, 15#u8, 16#u8, 17#u8, 18#u8, 19#u8, 20#u8,
    21#u8, 22#u8, 23#u8, 24#u8, 25#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 26#u8, 27#u8, 28#u8, 29#u8, 30#u8, 31#u8, 32#u8, 33#u8, 34#u8,
    35#u8, 36#u8, 37#u8, 38#u8, 39#u8, 40#u8, 41#u8, 42#u8, 43#u8, 44#u8,
    45#u8, 46#u8, 47#u8, 48#u8, 49#u8, 50#u8, 51#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8
    ]

/-- [base64_core::URL_SAFE_ENCODE]
    Source: 'rust/base64-core/src/lib.rs', lines 66:0-71:2
    Visibility: public -/
@[global_simps, irreducible]
def URL_SAFE_ENCODE : Array Std.U8 64#usize :=
  Array.make 64#usize [
    65#u8, 66#u8, 67#u8, 68#u8, 69#u8, 70#u8, 71#u8, 72#u8, 73#u8, 74#u8,
    75#u8, 76#u8, 77#u8, 78#u8, 79#u8, 80#u8, 81#u8, 82#u8, 83#u8, 84#u8,
    85#u8, 86#u8, 87#u8, 88#u8, 89#u8, 90#u8, 97#u8, 98#u8, 99#u8, 100#u8,
    101#u8, 102#u8, 103#u8, 104#u8, 105#u8, 106#u8, 107#u8, 108#u8, 109#u8,
    110#u8, 111#u8, 112#u8, 113#u8, 114#u8, 115#u8, 116#u8, 117#u8, 118#u8,
    119#u8, 120#u8, 121#u8, 122#u8, 48#u8, 49#u8, 50#u8, 51#u8, 52#u8, 53#u8,
    54#u8, 55#u8, 56#u8, 57#u8, 45#u8, 95#u8
    ]

/-- [base64_core::URL_SAFE_DECODE]
    Source: 'rust/base64-core/src/lib.rs', lines 73:0-90:2
    Visibility: public -/
@[global_simps, irreducible]
def URL_SAFE_DECODE : Array Std.U8 256#usize :=
  Array.make 256#usize [
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    62#u8, 255#u8, 255#u8, 52#u8, 53#u8, 54#u8, 55#u8, 56#u8, 57#u8, 58#u8,
    59#u8, 60#u8, 61#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 0#u8, 1#u8, 2#u8, 3#u8, 4#u8, 5#u8, 6#u8, 7#u8, 8#u8, 9#u8, 10#u8,
    11#u8, 12#u8, 13#u8, 14#u8, 15#u8, 16#u8, 17#u8, 18#u8, 19#u8, 20#u8,
    21#u8, 22#u8, 23#u8, 24#u8, 25#u8, 255#u8, 255#u8, 255#u8, 255#u8, 63#u8,
    255#u8, 26#u8, 27#u8, 28#u8, 29#u8, 30#u8, 31#u8, 32#u8, 33#u8, 34#u8,
    35#u8, 36#u8, 37#u8, 38#u8, 39#u8, 40#u8, 41#u8, 42#u8, 43#u8, 44#u8,
    45#u8, 46#u8, 47#u8, 48#u8, 49#u8, 50#u8, 51#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8, 255#u8,
    255#u8, 255#u8, 255#u8, 255#u8
    ]

/-- [base64_core::{impl core::clone::Clone for base64_core::DecodeError}::clone]:
    Source: 'rust/base64-core/src/lib.rs', lines 102:9-102:14
    Visibility: public -/
def DecodeError.Insts.CoreCloneClone.clone
  (self : DecodeError) : Result DecodeError := do
  ok self

/-- Trait implementation: [base64_core::{impl core::clone::Clone for base64_core::DecodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 102:9-102:14 -/
@[reducible]
def DecodeError.Insts.CoreCloneClone : core.clone.Clone DecodeError := {
  clone := DecodeError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [base64_core::{impl core::marker::Copy for base64_core::DecodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 102:16-102:20 -/
@[reducible]
def DecodeError.Insts.CoreMarkerCopy : core.marker.Copy DecodeError := {
  cloneInst := DecodeError.Insts.CoreCloneClone
}

/-- Trait implementation: [base64_core::{impl core::marker::StructuralPartialEq for base64_core::DecodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 102:22-102:31 -/
@[reducible]
def DecodeError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq DecodeError := {
}

/-- [base64_core::{impl core::cmp::PartialEq<base64_core::DecodeError> for base64_core::DecodeError}::eq]:
    Source: 'rust/base64-core/src/lib.rs', lines 102:22-102:31
    Visibility: public -/
def DecodeError.Insts.CoreCmpPartialEqDecodeError.eq
  (self : DecodeError) (other : DecodeError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | DecodeError.InvalidByte __self_0 __self_1 =>
      match other with
      | DecodeError.InvalidByte __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqU8.eq __self_1 __arg1_1)
        if b
        then lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        else ok false
      | DecodeError.InvalidLength _ => ok true
      | DecodeError.InvalidLastSymbol _ _ _ => ok true
      | DecodeError.InvalidPadding => ok true
    | DecodeError.InvalidLength __self_0 =>
      match other with
      | DecodeError.InvalidByte _ _ => ok true
      | DecodeError.InvalidLength __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | DecodeError.InvalidLastSymbol _ _ _ => ok true
      | DecodeError.InvalidPadding => ok true
    | DecodeError.InvalidLastSymbol __self_0 __self_1 __self_2 =>
      match other with
      | DecodeError.InvalidByte _ _ => ok true
      | DecodeError.InvalidLength _ => ok true
      | DecodeError.InvalidLastSymbol __arg1_0 __arg1_1 __arg1_2 =>
        let b ← lift (core.cmp.impls.PartialEqU8.eq __self_1 __arg1_1)
        if b
        then
          let b1 ← lift (core.cmp.impls.PartialEqU8.eq __self_2 __arg1_2)
          if b1
          then lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
          else ok false
        else ok false
      | DecodeError.InvalidPadding => ok true
    | DecodeError.InvalidPadding => ok true
  else ok false

/-- Trait implementation: [base64_core::{impl core::cmp::PartialEq<base64_core::DecodeError> for base64_core::DecodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 102:22-102:31 -/
@[reducible]
def DecodeError.Insts.CoreCmpPartialEqDecodeError : core.cmp.PartialEq
  DecodeError DecodeError := {
  eq := DecodeError.Insts.CoreCmpPartialEqDecodeError.eq
}

/-- [base64_core::{impl core::cmp::Eq for base64_core::DecodeError}::assert_fields_are_eq]:
    Source: 'rust/base64-core/src/lib.rs', lines 102:33-102:35
    Visibility: public -/
def DecodeError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : DecodeError) : Result Unit := do
  ok ()

/-- Trait implementation: [base64_core::{impl core::cmp::Eq for base64_core::DecodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 102:33-102:35 -/
@[reducible]
def DecodeError.Insts.CoreCmpEq : core.cmp.Eq DecodeError := {
  partialEqInst := DecodeError.Insts.CoreCmpPartialEqDecodeError
  assert_fields_are_eq := DecodeError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [base64_core::{impl core::clone::Clone for base64_core::EncodeError}::clone]:
    Source: 'rust/base64-core/src/lib.rs', lines 115:9-115:14
    Visibility: public -/
def EncodeError.Insts.CoreCloneClone.clone
  (self : EncodeError) : Result EncodeError := do
  ok self

/-- Trait implementation: [base64_core::{impl core::clone::Clone for base64_core::EncodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 115:9-115:14 -/
@[reducible]
def EncodeError.Insts.CoreCloneClone : core.clone.Clone EncodeError := {
  clone := EncodeError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [base64_core::{impl core::marker::Copy for base64_core::EncodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 115:16-115:20 -/
@[reducible]
def EncodeError.Insts.CoreMarkerCopy : core.marker.Copy EncodeError := {
  cloneInst := EncodeError.Insts.CoreCloneClone
}

/-- Trait implementation: [base64_core::{impl core::marker::StructuralPartialEq for base64_core::EncodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 115:22-115:31 -/
@[reducible]
def EncodeError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq EncodeError := {
}

/-- [base64_core::{impl core::cmp::PartialEq<base64_core::EncodeError> for base64_core::EncodeError}::eq]:
    Source: 'rust/base64-core/src/lib.rs', lines 115:22-115:31
    Visibility: public -/
def EncodeError.Insts.CoreCmpPartialEqEncodeError.eq
  (self : EncodeError) (other : EncodeError) : Result Bool := do
  ok true

/-- Trait implementation: [base64_core::{impl core::cmp::PartialEq<base64_core::EncodeError> for base64_core::EncodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 115:22-115:31 -/
@[reducible]
def EncodeError.Insts.CoreCmpPartialEqEncodeError : core.cmp.PartialEq
  EncodeError EncodeError := {
  eq := EncodeError.Insts.CoreCmpPartialEqEncodeError.eq
}

/-- [base64_core::{impl core::cmp::Eq for base64_core::EncodeError}::assert_fields_are_eq]:
    Source: 'rust/base64-core/src/lib.rs', lines 115:33-115:35
    Visibility: public -/
def EncodeError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : EncodeError) : Result Unit := do
  ok ()

/-- Trait implementation: [base64_core::{impl core::cmp::Eq for base64_core::EncodeError}]
    Source: 'rust/base64-core/src/lib.rs', lines 115:33-115:35 -/
@[reducible]
def EncodeError.Insts.CoreCmpEq : core.cmp.Eq EncodeError := {
  partialEqInst := EncodeError.Insts.CoreCmpPartialEqEncodeError
  assert_fields_are_eq := EncodeError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [base64_core::encoded_len]:
    Source: 'rust/base64-core/src/lib.rs', lines 129:0-143:1
    Visibility: public -/
def encoded_len (bytes_len : Std.Usize) : Result (Option Std.Usize) := do
  let rem ← bytes_len % 3#usize
  let complete_input_chunks ← bytes_len / 3#usize
  let o ← lift (Usize.checked_mul complete_input_chunks 4#usize)
  match o with
  | none => ok none
  | some n => if rem > 0#usize
              then ok (Usize.checked_add n 4#usize)
              else ok o

/-- [base64_core::encode_quads::LOW_SIX_BITS_U8]
    Source: 'rust/base64-core/src/lib.rs', lines 154:4-154:37 -/
@[global_simps, irreducible] def encode_quads.LOW_SIX_BITS_U8 : Std.U8 := 63#u8

/-- [base64_core::encode_quads]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 162:4-174:5
    Visibility: public -/
@[rust_loop_body]
def encode_quads_loop.body
  (input : Slice Std.U8) (encode_table : Array Std.U8 64#usize)
  (start_of_rem : Std.Usize) (output : Slice Std.U8) (input_index : Std.Usize)
  (output_index : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × Std.Usize × Std.Usize) ((Slice
    Std.U8) × Std.Usize))
  := do
  if input_index < start_of_rem
  then
    let b0 ← Slice.index_usize input input_index
    let i ← input_index + 1#usize
    let b1 ← Slice.index_usize input i
    let i1 ← input_index + 2#usize
    let b2 ← Slice.index_usize input i1
    let i2 ← b0 >>> 2#i32
    let i3 ← lift (UScalar.cast .Usize i2)
    let i4 ← Array.index_usize encode_table i3
    let output1 ← Slice.update output output_index i4
    let i5 ← b0 <<< 4#i32
    let i6 ← b1 >>> 4#i32
    let i7 ← lift (i5 ||| i6)
    let i8 ← lift (i7 &&& encode_quads.LOW_SIX_BITS_U8)
    let i9 ← lift (UScalar.cast .Usize i8)
    let i10 ← Array.index_usize encode_table i9
    let i11 ← output_index + 1#usize
    let output2 ← Slice.update output1 i11 i10
    let i12 ← b1 <<< 2#i32
    let i13 ← b2 >>> 6#i32
    let i14 ← lift (i12 ||| i13)
    let i15 ← lift (i14 &&& encode_quads.LOW_SIX_BITS_U8)
    let i16 ← lift (UScalar.cast .Usize i15)
    let i17 ← Array.index_usize encode_table i16
    let i18 ← output_index + 2#usize
    let output3 ← Slice.update output2 i18 i17
    let i19 ← lift (b2 &&& encode_quads.LOW_SIX_BITS_U8)
    let i20 ← lift (UScalar.cast .Usize i19)
    let i21 ← Array.index_usize encode_table i20
    let i22 ← output_index + 3#usize
    let s ← Slice.update output3 i22 i21
    let input_index1 ← input_index + 3#usize
    let output_index1 ← output_index + 4#usize
    ok (cont (s, input_index1, output_index1))
  else ok (done (output, output_index))

/-- [base64_core::encode_quads]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 162:4-174:5
    Visibility: public -/
@[rust_loop]
def encode_quads_loop
  (input : Slice Std.U8) (output : Slice Std.U8)
  (encode_table : Array Std.U8 64#usize) (start_of_rem : Std.Usize)
  (input_index : Std.Usize) (output_index : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (output1, input_index1, output_index1) => encode_quads_loop.body input
      encode_table start_of_rem output1 input_index1 output_index1)
    (output, input_index, output_index)

/-- [base64_core::encode_quads]:
    Source: 'rust/base64-core/src/lib.rs', lines 153:0-191:1
    Visibility: public -/
def encode_quads
  (input : Slice Std.U8) (output : Slice Std.U8)
  (encode_table : Array Std.U8 64#usize) :
  Result (Std.Usize × (Slice Std.U8))
  := do
  let i := Slice.len input
  let rem ← i % 3#usize
  let i1 := Slice.len input
  let start_of_rem ← i1 - rem
  let (output1, output_index) ←
    encode_quads_loop input output encode_table start_of_rem 0#usize 0#usize
  if rem = 2#usize
  then
    let i2 ← Slice.index_usize input start_of_rem
    let i3 ← i2 >>> 2#i32
    let i4 ← lift (UScalar.cast .Usize i3)
    let i5 ← Array.index_usize encode_table i4
    let output2 ← Slice.update output1 output_index i5
    let i6 ← i2 <<< 4#i32
    let i7 ← start_of_rem + 1#usize
    let i8 ← Slice.index_usize input i7
    let i9 ← i8 >>> 4#i32
    let i10 ← lift (i6 ||| i9)
    let i11 ← lift (i10 &&& encode_quads.LOW_SIX_BITS_U8)
    let i12 ← lift (UScalar.cast .Usize i11)
    let i13 ← Array.index_usize encode_table i12
    let i14 ← output_index + 1#usize
    let output3 ← Slice.update output2 i14 i13
    let i15 ← Slice.index_usize input i7
    let i16 ← i15 <<< 2#i32
    let i17 ← lift (i16 &&& encode_quads.LOW_SIX_BITS_U8)
    let i18 ← lift (UScalar.cast .Usize i17)
    let i19 ← Array.index_usize encode_table i18
    let i20 ← output_index + 2#usize
    let output4 ← Slice.update output3 i20 i19
    let output_index1 ← output_index + 3#usize
    ok (output_index1, output4)
  else
    if rem = 1#usize
    then
      let i2 ← Slice.index_usize input start_of_rem
      let i3 ← i2 >>> 2#i32
      let i4 ← lift (UScalar.cast .Usize i3)
      let i5 ← Array.index_usize encode_table i4
      let output2 ← Slice.update output1 output_index i5
      let i6 ← i2 <<< 4#i32
      let i7 ← lift (i6 &&& encode_quads.LOW_SIX_BITS_U8)
      let i8 ← lift (UScalar.cast .Usize i7)
      let i9 ← Array.index_usize encode_table i8
      let i10 ← output_index + 1#usize
      let output3 ← Slice.update output2 i10 i9
      let output_index1 ← output_index + 2#usize
      ok (output_index1, output3)
    else ok (output_index, output1)

/-- [base64_core::add_padding]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 202:4-205:5
    Visibility: public -/
@[rust_loop_body]
def add_padding_loop.body
  (unpadded_output_len : Std.Usize) (pad_bytes : Std.Usize)
  (output : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × Std.Usize) (Slice Std.U8))
  := do
  if i < pad_bytes
  then
    let i1 ← unpadded_output_len + i
    let s ← Slice.update output i1 PAD_BYTE
    let i2 ← i + 1#usize
    ok (cont (s, i2))
  else ok (done output)

/-- [base64_core::add_padding]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 202:4-205:5
    Visibility: public -/
@[rust_loop]
def add_padding_loop
  (unpadded_output_len : Std.Usize) (output : Slice Std.U8)
  (pad_bytes : Std.Usize) (i : Std.Usize) :
  Result (Slice Std.U8)
  := do
  loop
    (fun (output1, i1) => add_padding_loop.body unpadded_output_len pad_bytes
      output1 i1)
    (output, i)

/-- [base64_core::add_padding]:
    Source: 'rust/base64-core/src/lib.rs', lines 198:0-208:1
    Visibility: public -/
def add_padding
  (unpadded_output_len : Std.Usize) (output : Slice Std.U8) :
  Result (Std.Usize × (Slice Std.U8))
  := do
  let i ← unpadded_output_len % 4#usize
  let i1 ← 4#usize - i
  let pad_bytes ← i1 % 4#usize
  let output1 ← add_padding_loop unpadded_output_len output pad_bytes 0#usize
  ok (pad_bytes, output1)

/-- [base64_core::encode_slice]:
    Source: 'rust/base64-core/src/lib.rs', lines 214:0-218:1
    Visibility: public -/
def encode_slice
  (input : Slice Std.U8) (output : Slice Std.U8)
  (encode_table : Array Std.U8 64#usize) :
  Result (Std.Usize × (Slice Std.U8))
  := do
  let (b64_bytes_written, output1) ← encode_quads input output encode_table
  let (padding_bytes, output2) ← add_padding b64_bytes_written output1
  let i ← b64_bytes_written + padding_bytes
  ok (i, output2)

/-- [base64_core::encode_alloc]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 233:4-236:5
    Visibility: public -/
@[rust_loop_body]
def encode_alloc_loop.body
  (encoded_size : Std.Usize) (buf : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < encoded_size
  then
    let buf1 ← alloc.vec.Vec.push buf 0#u8
    let i1 ← i + 1#usize
    ok (cont (buf1, i1))
  else ok (done buf)

/-- [base64_core::encode_alloc]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 233:4-236:5
    Visibility: public -/
@[rust_loop]
def encode_alloc_loop
  (encoded_size : Std.Usize) (buf : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (buf1, i1) => encode_alloc_loop.body encoded_size buf1 i1)
    (buf, i)

/-- [base64_core::encode_alloc]:
    Source: 'rust/base64-core/src/lib.rs', lines 225:0-242:1
    Visibility: public -/
def encode_alloc
  (input : Slice Std.U8) (encode_table : Array Std.U8 64#usize) :
  Result (core.result.Result (alloc.vec.Vec Std.U8) EncodeError)
  := do
  let i := Slice.len input
  let o ← encoded_len i
  match o with
  | none => ok (core.result.Result.Err EncodeError.LengthOverflow)
  | some n =>
    let buf ← encode_alloc_loop n (alloc.vec.Vec.new Std.U8) 0#usize
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut buf)
    let (_, s1) ← encode_slice input s encode_table
    let buf1 := deref_mut_back s1
    ok (core.result.Result.Ok buf1)

/-- [base64_core::decoded_len_estimate]:
    Source: 'rust/base64-core/src/lib.rs', lines 251:0-254:1
    Visibility: public -/
def decoded_len_estimate (encoded_len1 : Std.Usize) : Result Std.Usize := do
  let rem ← encoded_len1 % 4#usize
  let i ← encoded_len1 / 4#usize
  let i1 ← if rem > 0#usize
             then ok 1#usize
             else ok 0#usize
  let i2 ← i + i1
  i2 * 3#usize

/-- [base64_core::complete_quads_len]:
    Source: 'rust/base64-core/src/lib.rs', lines 263:0-292:1 -/
def complete_quads_len
  (input : Slice Std.U8) (input_len_rem : Std.Usize)
  (decode_table : Array Std.U8 256#usize) :
  Result (core.result.Result Std.Usize DecodeError)
  := do
  if input_len_rem = 1#usize
  then
    let i := Slice.len input
    let i1 ← i - 1#usize
    let last_byte ← Slice.index_usize input i1
    if last_byte != PAD_BYTE
    then
      let i2 ← lift (UScalar.cast .Usize last_byte)
      let i3 ← Array.index_usize decode_table i2
      if i3 = INVALID_VALUE
      then
        let i4 := Slice.len input
        let i5 ← i4 - 1#usize
        ok (core.result.Result.Err (DecodeError.InvalidByte i5 last_byte))
      else
        let i4 := Slice.len input
        let after_rem ← i4 - input_len_rem
        if input_len_rem = 0#usize
        then
          if after_rem >= 4#usize
          then
            let input_complete_nonterminal_quads_len ← after_rem - 4#usize
            ok (core.result.Result.Ok input_complete_nonterminal_quads_len)
          else ok (core.result.Result.Ok 0#usize)
        else ok (core.result.Result.Ok after_rem)
    else
      let i2 := Slice.len input
      let after_rem ← i2 - input_len_rem
      if input_len_rem = 0#usize
      then
        if after_rem >= 4#usize
        then
          let input_complete_nonterminal_quads_len ← after_rem - 4#usize
          ok (core.result.Result.Ok input_complete_nonterminal_quads_len)
        else ok (core.result.Result.Ok 0#usize)
      else ok (core.result.Result.Ok after_rem)
  else
    let i := Slice.len input
    let after_rem ← i - input_len_rem
    if input_len_rem = 0#usize
    then
      if after_rem >= 4#usize
      then
        let input_complete_nonterminal_quads_len ← after_rem - 4#usize
        ok (core.result.Result.Ok input_complete_nonterminal_quads_len)
      else ok (core.result.Result.Ok 0#usize)
    else ok (core.result.Result.Ok after_rem)

/-- [base64_core::decode_chunk_4]:
    Source: 'rust/base64-core/src/lib.rs', lines 300:0-340:1 -/
def decode_chunk_4
  (input : Slice Std.U8) (input_index : Std.Usize) (output : Slice Std.U8)
  (output_index : Std.Usize) (decode_table : Array Std.U8 256#usize) :
  Result ((core.result.Result Unit DecodeError) × (Slice Std.U8))
  := do
  let b0 ← Slice.index_usize input input_index
  let i ← lift (UScalar.cast .Usize b0)
  let morsel ← Array.index_usize decode_table i
  if morsel = INVALID_VALUE
  then
    ok (core.result.Result.Err (DecodeError.InvalidByte input_index b0),
      output)
  else
    let i1 ← lift (UScalar.cast .U32 morsel)
    let accum ← i1 <<< 26#i32
    let i2 ← input_index + 1#usize
    let b1 ← Slice.index_usize input i2
    let i3 ← lift (UScalar.cast .Usize b1)
    let morsel1 ← Array.index_usize decode_table i3
    if morsel1 = INVALID_VALUE
    then ok (core.result.Result.Err (DecodeError.InvalidByte i2 b1), output)
    else
      let i4 ← lift (UScalar.cast .U32 morsel1)
      let i5 ← i4 <<< 20#i32
      let accum1 ← lift (accum ||| i5)
      let i6 ← input_index + 2#usize
      let b2 ← Slice.index_usize input i6
      let i7 ← lift (UScalar.cast .Usize b2)
      let morsel2 ← Array.index_usize decode_table i7
      if morsel2 = INVALID_VALUE
      then ok (core.result.Result.Err (DecodeError.InvalidByte i6 b2), output)
      else
        let i8 ← lift (UScalar.cast .U32 morsel2)
        let i9 ← i8 <<< 14#i32
        let accum2 ← lift (accum1 ||| i9)
        let i10 ← input_index + 3#usize
        let b3 ← Slice.index_usize input i10
        let i11 ← lift (UScalar.cast .Usize b3)
        let morsel3 ← Array.index_usize decode_table i11
        if morsel3 = INVALID_VALUE
        then
          ok (core.result.Result.Err (DecodeError.InvalidByte i10 b3), output)
        else
          let i12 ← lift (UScalar.cast .U32 morsel3)
          let i13 ← i12 <<< 8#i32
          let accum3 ← lift (accum2 ||| i13)
          let i14 ← accum3 >>> 24#i32
          let i15 ← lift (UScalar.cast .U8 i14)
          let output1 ← Slice.update output output_index i15
          let i16 ← accum3 >>> 16#i32
          let i17 ← output_index + 1#usize
          let i18 ← lift (UScalar.cast .U8 i16)
          let output2 ← Slice.update output1 i17 i18
          let i19 ← accum3 >>> 8#i32
          let i20 ← output_index + 2#usize
          let i21 ← lift (UScalar.cast .U8 i19)
          let output3 ← Slice.update output2 i20 i21
          ok (core.result.Result.Ok (), output3)

/-- [base64_core::suffix_scan_step]:
    Source: 'rust/base64-core/src/lib.rs', lines 379:0-431:1 -/
def suffix_scan_step
  (st : SuffixScan) (input_index : Std.Usize) (leftover_index : Std.Usize)
  (b : Std.U8) (decode_table : Array Std.U8 256#usize) :
  Result SuffixScan
  := do
  let b1 := core.option.Option.is_some st.err
  if b1
  then ok st
  else
    if b = PAD_BYTE
    then
      if leftover_index < 2#usize
      then
        let bad_padding_index ← input_index + leftover_index
        ok
          { st with err := (some (DecodeError.InvalidByte bad_padding_index b))
          }
      else
        let i ←
          if st.padding_bytes_count = 0#usize
          then ok leftover_index
          else ok st.first_padding_offset
        let i1 ← st.padding_bytes_count + 1#usize
        ok { st with padding_bytes_count := i1, first_padding_offset := i }
    else
      if st.padding_bytes_count > 0#usize
      then
        let i ← input_index + st.first_padding_offset
        ok { st with err := (some (DecodeError.InvalidByte i PAD_BYTE)) }
      else
        let i ← lift (UScalar.cast .Usize b)
        let morsel ← Array.index_usize decode_table i
        if morsel = INVALID_VALUE
        then
          let i1 ← input_index + leftover_index
          ok { st with err := (some (DecodeError.InvalidByte i1 b)) }
        else
          let (i1, i2, i3, i4) ←
            if st.morsels_in_leftover = 0#usize
            then ok (morsel, st.morsel1, st.morsel2, st.morsel3)
            else
              do
              let (i5, i6, i7) ←
                if st.morsels_in_leftover = 1#usize
                then ok (morsel, st.morsel2, st.morsel3)
                else
                  do
                  let (i8, i9) ←
                    if st.morsels_in_leftover = 2#usize
                    then ok (morsel, st.morsel3)
                    else ok (st.morsel2, morsel)
                  ok (st.morsel1, i8, i9)
              ok (st.morsel0, i5, i6, i7)
          let i5 ← st.morsels_in_leftover + 1#usize
          ok
            {
              st
                with
                morsels_in_leftover := i5,
                last_symbol := b,
                last_symbol_value := morsel,
                morsel0 := i1,
                morsel1 := i2,
                morsel2 := i3,
                morsel3 := i4
            }

/-- [base64_core::decode_suffix]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 517:4-523:5 -/
@[rust_loop_body]
def decode_suffix_loop0.body
  (leftover_bytes_to_append : Std.Usize) (output : Slice Std.U8)
  (output_index : Std.Usize) (leftover_num : Std.U32) (k : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × Std.Usize × Std.U32 × Std.Usize)
    ((Slice Std.U8) × Std.Usize))
  := do
  if k < leftover_bytes_to_append
  then
    let i ← leftover_num >>> 24#i32
    let hi_byte ← lift (UScalar.cast .U8 i)
    let leftover_num1 ← leftover_num <<< 8#i32
    let s ← Slice.update output output_index hi_byte
    let output_index1 ← output_index + 1#usize
    let k1 ← k + 1#usize
    ok (cont (s, output_index1, leftover_num1, k1))
  else ok (done (output, output_index))

/-- [base64_core::decode_suffix]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 517:4-523:5 -/
@[rust_loop]
def decode_suffix_loop0
  (output : Slice Std.U8) (output_index : Std.Usize)
  (leftover_bytes_to_append : Std.Usize) (leftover_num : Std.U32)
  (k : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (output1, output_index1, leftover_num1, k1) =>
      decode_suffix_loop0.body leftover_bytes_to_append output1 output_index1
      leftover_num1 k1)
    (output, output_index, leftover_num, k)

/-- [base64_core::decode_suffix]: loop body 1:
    Source: 'rust/base64-core/src/lib.rs', lines 517:4-523:5 -/
@[rust_loop_body]
def decode_suffix_loop1.body
  (leftover_bytes_to_append : Std.Usize) (output : Slice Std.U8)
  (output_index : Std.Usize) (leftover_num : Std.U32) (k : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × Std.Usize × Std.U32 × Std.Usize)
    ((Slice Std.U8) × Std.Usize))
  := do
  if k < leftover_bytes_to_append
  then
    let i ← leftover_num >>> 24#i32
    let hi_byte ← lift (UScalar.cast .U8 i)
    let leftover_num1 ← leftover_num <<< 8#i32
    let s ← Slice.update output output_index hi_byte
    let output_index1 ← output_index + 1#usize
    let k1 ← k + 1#usize
    ok (cont (s, output_index1, leftover_num1, k1))
  else ok (done (output, output_index))

/-- [base64_core::decode_suffix]: loop 1:
    Source: 'rust/base64-core/src/lib.rs', lines 517:4-523:5 -/
@[rust_loop]
def decode_suffix_loop1
  (output : Slice Std.U8) (output_index : Std.Usize)
  (leftover_bytes_to_append : Std.Usize) (leftover_num : Std.U32)
  (k : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (output1, output_index1, leftover_num1, k1) =>
      decode_suffix_loop1.body leftover_bytes_to_append output1 output_index1
      leftover_num1 k1)
    (output, output_index, leftover_num, k)

/-- [base64_core::decode_suffix]:
    Source: 'rust/base64-core/src/lib.rs', lines 433:0-526:1 -/
def decode_suffix
  (input : Slice Std.U8) (input_index : Std.Usize) (output : Slice Std.U8)
  (output_index_start : Std.Usize) (decode_table : Array Std.U8 256#usize) :
  Result ((core.result.Result Std.Usize DecodeError) × (Slice Std.U8))
  := do
  let len := Slice.len input
  let st ←
    if input_index < len
    then
      do
      let i ← Slice.index_usize input input_index
      suffix_scan_step
        {
          morsels_in_leftover := 0#usize,
          padding_bytes_count := 0#usize,
          first_padding_offset := 0#usize,
          last_symbol := 0#u8,
          last_symbol_value := 0#u8,
          morsel0 := 0#u8,
          morsel1 := 0#u8,
          morsel2 := 0#u8,
          morsel3 := 0#u8,
          err := none
        } input_index 0#usize i decode_table
    else
      ok
        ({
           morsels_in_leftover := 0#usize,
           padding_bytes_count := 0#usize,
           first_padding_offset := 0#usize,
           last_symbol := 0#u8,
           last_symbol_value := 0#u8,
           morsel0 := 0#u8,
           morsel1 := 0#u8,
           morsel2 := 0#u8,
           morsel3 := 0#u8,
           err := none
         } : SuffixScan)
  let i ← input_index + 1#usize
  let st1 ←
    if i < len
    then
      do
      let i1 ← Slice.index_usize input i
      suffix_scan_step st input_index 1#usize i1 decode_table
    else ok st
  let i1 ← input_index + 2#usize
  let st2 ←
    if i1 < len
    then
      do
      let i2 ← Slice.index_usize input i1
      suffix_scan_step st1 input_index 2#usize i2 decode_table
    else ok st1
  let i2 ← input_index + 3#usize
  let st3 ←
    if i2 < len
    then
      do
      let i3 ← Slice.index_usize input i2
      suffix_scan_step st2 input_index 3#usize i3 decode_table
    else ok st2
  match st3.err with
  | none =>
    let b ← core.slice.Slice.is_empty input
    if b
    then
      let i3 ← st3.padding_bytes_count + st3.morsels_in_leftover
      let i4 ← i3 % 4#usize
      if i4 != 0#usize
      then ok (core.result.Result.Err DecodeError.InvalidPadding, output)
      else
        let i5 ← st3.morsels_in_leftover * 6#usize
        let leftover_bytes_to_append ← i5 / 8#usize
        let i6 ← lift (UScalar.cast .U32 st3.morsel0)
        let i7 ← i6 <<< 26#i32
        let i8 ← lift (UScalar.cast .U32 st3.morsel1)
        let i9 ← i8 <<< 20#i32
        let i10 ← lift (i7 ||| i9)
        let i11 ← lift (UScalar.cast .U32 st3.morsel2)
        let i12 ← i11 <<< 14#i32
        let i13 ← lift (i10 ||| i12)
        let i14 ← lift (UScalar.cast .U32 st3.morsel3)
        let i15 ← i14 <<< 8#i32
        let leftover_num ← lift (i13 ||| i15)
        let i16 ← lift (~~~ 0#u32)
        let i17 ← leftover_bytes_to_append * 8#usize
        let mask ← i16 >>> i17
        let i18 ← lift (leftover_num &&& mask)
        if i18 != 0#u32
        then
          let i19 ← input_index + st3.morsels_in_leftover
          let i20 ← i19 - 1#usize
          ok (core.result.Result.Err (DecodeError.InvalidLastSymbol i20
            st3.last_symbol st3.last_symbol_value), output)
        else
          let (output1, output_index) ←
            decode_suffix_loop0 output output_index_start
              leftover_bytes_to_append leftover_num 0#usize
          ok (core.result.Result.Ok output_index, output1)
    else
      if st3.morsels_in_leftover < 2#usize
      then
        let i3 ← input_index + st3.morsels_in_leftover
        ok (core.result.Result.Err (DecodeError.InvalidLength i3), output)
      else
        let i3 ← st3.padding_bytes_count + st3.morsels_in_leftover
        let i4 ← i3 % 4#usize
        if i4 != 0#usize
        then ok (core.result.Result.Err DecodeError.InvalidPadding, output)
        else
          let i5 ← st3.morsels_in_leftover * 6#usize
          let leftover_bytes_to_append ← i5 / 8#usize
          let i6 ← lift (UScalar.cast .U32 st3.morsel0)
          let i7 ← i6 <<< 26#i32
          let i8 ← lift (UScalar.cast .U32 st3.morsel1)
          let i9 ← i8 <<< 20#i32
          let i10 ← lift (i7 ||| i9)
          let i11 ← lift (UScalar.cast .U32 st3.morsel2)
          let i12 ← i11 <<< 14#i32
          let i13 ← lift (i10 ||| i12)
          let i14 ← lift (UScalar.cast .U32 st3.morsel3)
          let i15 ← i14 <<< 8#i32
          let leftover_num ← lift (i13 ||| i15)
          let i16 ← lift (~~~ 0#u32)
          let i17 ← leftover_bytes_to_append * 8#usize
          let mask ← i16 >>> i17
          let i18 ← lift (leftover_num &&& mask)
          if i18 != 0#u32
          then
            let i19 ← input_index + st3.morsels_in_leftover
            let i20 ← i19 - 1#usize
            ok (core.result.Result.Err (DecodeError.InvalidLastSymbol i20
              st3.last_symbol st3.last_symbol_value), output)
          else
            let (output1, output_index) ←
              decode_suffix_loop1 output output_index_start
                leftover_bytes_to_append leftover_num 0#usize
            ok (core.result.Result.Ok output_index, output1)
  | some e => ok (core.result.Result.Err e, output)

/-- [base64_core::decode_slice]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 1:0-568:5
    Visibility: public -/
@[rust_loop_body]
def decode_slice_loop.body
  (input : Slice Std.U8) (decode_table : Array Std.U8 256#usize)
  (input_complete_nonterminal_quads_len : Std.Usize) (output : Slice Std.U8)
  (quad_err : Option DecodeError) (input_index : Std.Usize)
  (output_index : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × (Option DecodeError) × Std.Usize ×
    Std.Usize) ((Slice Std.U8) × (Option DecodeError) × Std.Usize ×
    Std.Usize))
  := do
  let b := core.option.Option.is_none quad_err
  if b
  then
    if input_index < input_complete_nonterminal_quads_len
    then
      let (r, output1) ←
        decode_chunk_4 input input_index output output_index decode_table
      match r with
      | core.result.Result.Ok _ =>
        let input_index1 ← input_index + 4#usize
        let output_index1 ← output_index + 3#usize
        ok (cont (output1, quad_err, input_index1, output_index1))
      | core.result.Result.Err e =>
        ok (cont (output1, some e, input_index, output_index))
    else ok (done (output, quad_err, input_index, output_index))
  else ok (done (output, quad_err, input_index, output_index))

/-- [base64_core::decode_slice]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 1:0-568:5
    Visibility: public -/
@[rust_loop]
def decode_slice_loop
  (input : Slice Std.U8) (output : Slice Std.U8)
  (decode_table : Array Std.U8 256#usize)
  (input_complete_nonterminal_quads_len : Std.Usize)
  (quad_err : Option DecodeError) (input_index : Std.Usize)
  (output_index : Std.Usize) :
  Result ((Slice Std.U8) × (Option DecodeError) × Std.Usize × Std.Usize)
  := do
  loop
    (fun (output1, quad_err1, input_index1, output_index1) =>
      decode_slice_loop.body input decode_table
      input_complete_nonterminal_quads_len output1 quad_err1 input_index1
      output_index1)
    (output, quad_err, input_index, output_index)

/-- [base64_core::decode_slice]:
    Source: 'rust/base64-core/src/lib.rs', lines 536:0-574:1
    Visibility: public -/
def decode_slice
  (input : Slice Std.U8) (output : Slice Std.U8)
  (decode_table : Array Std.U8 256#usize) :
  Result ((core.result.Result Std.Usize DecodeError) × (Slice Std.U8))
  := do
  let i := Slice.len input
  let rem ← i % 4#usize
  let r ← complete_quads_len input rem decode_table
  match r with
  | core.result.Result.Ok n =>
    let (output1, quad_err, input_index, output_index) ←
      decode_slice_loop input output decode_table n none 0#usize 0#usize
    match quad_err with
    | none => decode_suffix input input_index output1 output_index decode_table
    | some e => ok (core.result.Result.Err e, output1)
  | core.result.Result.Err _ => ok (r, output)

/-- [base64_core::decode_alloc]: loop body 0:
    Source: 'rust/base64-core/src/lib.rs', lines 586:4-589:5
    Visibility: public -/
@[rust_loop_body]
def decode_alloc_loop0.body
  (estimate : Std.Usize) (buf : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < estimate
  then
    let buf1 ← alloc.vec.Vec.push buf 0#u8
    let i1 ← i + 1#usize
    ok (cont (buf1, i1))
  else ok (done buf)

/-- [base64_core::decode_alloc]: loop 0:
    Source: 'rust/base64-core/src/lib.rs', lines 586:4-589:5
    Visibility: public -/
@[rust_loop]
def decode_alloc_loop0
  (estimate : Std.Usize) (buf : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (buf1, i1) => decode_alloc_loop0.body estimate buf1 i1)
    (buf, i)

/-- [base64_core::decode_alloc]: loop body 1:
    Source: 'rust/base64-core/src/lib.rs', lines 599:4-602:5
    Visibility: public -/
@[rust_loop_body]
def decode_alloc_loop1.body
  (buf : alloc.vec.Vec Std.U8) (len : Std.Usize) (out : alloc.vec.Vec Std.U8)
  (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if j < len
  then
    let i ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) buf j
    let out1 ← alloc.vec.Vec.push out i
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [base64_core::decode_alloc]: loop 1:
    Source: 'rust/base64-core/src/lib.rs', lines 599:4-602:5
    Visibility: public -/
@[rust_loop]
def decode_alloc_loop1
  (buf : alloc.vec.Vec Std.U8) (len : Std.Usize) (out : alloc.vec.Vec Std.U8)
  (j : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, j1) => decode_alloc_loop1.body buf len out1 j1)
    (out, j)

/-- [base64_core::decode_alloc]:
    Source: 'rust/base64-core/src/lib.rs', lines 581:0-604:1
    Visibility: public -/
def decode_alloc
  (input : Slice Std.U8) (decode_table : Array Std.U8 256#usize) :
  Result (core.result.Result (alloc.vec.Vec Std.U8) DecodeError)
  := do
  let i := Slice.len input
  let estimate ← decoded_len_estimate i
  let buf ← decode_alloc_loop0 estimate (alloc.vec.Vec.new Std.U8) 0#usize
  let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut buf)
  let (r, s1) ← decode_slice input s decode_table
  match r with
  | core.result.Result.Ok n =>
    let buf1 := deref_mut_back s1
    let out ← decode_alloc_loop1 buf1 n (alloc.vec.Vec.new Std.U8) 0#usize
    ok (core.result.Result.Ok out)
  | core.result.Result.Err e => ok (core.result.Result.Err e)

end base64_core
