-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [base64_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace base64_core

/-- [base64_core::DecodeError]
    Source: 'rust/base64-core/src/lib.rs', lines 103:0-113:1
    Visibility: public -/
@[discriminant isize]
inductive DecodeError where
| InvalidByte : Std.Usize → Std.U8 → DecodeError
| InvalidLength : Std.Usize → DecodeError
| InvalidLastSymbol : Std.Usize → Std.U8 → Std.U8 → DecodeError
| InvalidPadding : DecodeError

/-- [base64_core::EncodeError]
    Source: 'rust/base64-core/src/lib.rs', lines 116:0-119:1
    Visibility: public -/
@[discriminant isize]
inductive EncodeError where
| LengthOverflow : EncodeError

/-- [base64_core::SuffixScan]
    Source: 'rust/base64-core/src/lib.rs', lines 363:0-375:1 -/
structure SuffixScan where
  morsels_in_leftover : Std.Usize
  padding_bytes_count : Std.Usize
  first_padding_offset : Std.Usize
  last_symbol : Std.U8
  last_symbol_value : Std.U8
  morsel0 : Std.U8
  morsel1 : Std.U8
  morsel2 : Std.U8
  morsel3 : Std.U8
  err : Option DecodeError

end base64_core
